(function (root, factory) {
  const library = factory();
  root.JUNNUO_LIBRARY = library;
  if (typeof module === "object" && module.exports) {
    module.exports = library;
  }
})(typeof self !== "undefined" ? self : this, function () {
  const CATEGORIES = [
    { id: "pressure-fryers", name: "Pressure Fryers" },
    { id: "open-fryers", name: "Open Fryers" },
    { id: "holding-cabinets", name: "Holding Cabinets" },
    { id: "marinating-equipment", name: "Marinating Equipment" },
    { id: "preparation-equipment", name: "Preparation Equipment" },
    { id: "refrigeration-equipment", name: "Refrigeration Equipment" },
    { id: "accessories", name: "Accessories" },
  ];

  const PRODUCTS = [
    {
      id: "ya-900",
      model: "YA-900",
      category: "marinating-equipment",
      name: "JUNNUO Marinating Machine YA-900",
      description: "Commercial marinating machine for food preparation workflows.",
      specs: ["Voltage: 220V/50Hz", "Power: 0.2 kW", "Drum speed: 32 r/min", "Machine size: 995 x 445 x 860 mm"],
      sellingPoints: ["Compact commercial structure", "Suitable for restaurant preparation rooms"],
      applications: ["Meat preparation", "Restaurant kitchens", "Central kitchens"],
      packageInfo: ["Carton packing size: 1080 x 570 x 950 mm", "Net weight: 40 kg", "Gross weight: 50 kg", "Carton with plywood frame"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "ya-900a",
      model: "YA-900A",
      category: "marinating-equipment",
      name: "JUNNUO Vacuum Marinator YA-900A",
      description: "Vacuum marinating equipment for improving food preparation efficiency.",
      specs: ["Voltage: 220V/50Hz", "Power: 1.18 kW", "Drum speed: 32 r/min", "Machine size: 995 x 445 x 860 mm"],
      sellingPoints: ["Vacuum marinating function", "Designed for commercial kitchen use"],
      applications: ["Chicken preparation", "Meat marination", "Food processing rooms"],
      packageInfo: ["Carton packing size: 1080 x 570 x 950 mm", "Net weight: 50 kg", "Gross weight: 65 kg", "Carton with plywood frame"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "jn-4",
      model: "JN-4",
      category: "holding-cabinets",
      name: "JUNNUO Patty Holding Cabinet JN-4",
      description: "Compact holding cabinet for keeping patties warm before service.",
      specs: ["Voltage: 220V/50Hz", "Power: 1.2 kW", "Machine size: 560 x 440 x 320 mm"],
      sellingPoints: ["Compact countertop format", "Suitable for fast food preparation lines"],
      applications: ["Burger shops", "Fast food kitchens", "Prepared food holding"],
      packageInfo: ["Packing size: 642 x 403 x 520 mm", "Net weight: 50 kg", "Gross weight: 65 kg", "Carton with plywood frame"],
      notes: "Specification requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "jn-6",
      model: "JN-6",
      category: "holding-cabinets",
      name: "JUNNUO Patty Holding Cabinet JN-6",
      description: "Wider patty holding cabinet for commercial food service operations.",
      specs: ["Voltage: 220V/50Hz", "Power: 1.8 kW", "Machine size: 750 x 440 x 320 mm"],
      sellingPoints: ["Larger holding width", "Built for repeated commercial service"],
      applications: ["Burger shops", "Fast food kitchens", "Prepared food holding"],
      packageInfo: ["Packing size: 840 x 530 x 530 mm", "Net weight: 50 kg", "Gross weight: 65 kg", "Carton with plywood frame"],
      notes: "Specification requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "jn-2p",
      model: "JN-2P",
      category: "preparation-equipment",
      name: "JUNNUO Electric Breading Station JN-2P",
      description: "Electric breading station with spiral brush for fried food preparation.",
      specs: ["Voltage: 220V/50Hz", "Power: 0.18 kW", "Machine size: 1152 x 450 x 850 mm"],
      sellingPoints: ["Electric operation", "Designed for breading workflows"],
      applications: ["Fried chicken preparation", "Restaurant kitchens", "Food preparation lines"],
      packageInfo: ["Packing size: 1230 x 530 x 960 mm", "Net weight: 53 kg", "Gross weight: 65 kg", "Plywood packing"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "vertical-burger-machine-48l",
      model: "48L",
      category: "preparation-equipment",
      name: "JUNNUO Vertical Burger Machine 48L",
      description: "Vertical burger machine for commercial food preparation.",
      specs: ["Voltage: 220V/50Hz", "Power: 2 kW", "Machine size: 460 x 350 x 610 mm"],
      sellingPoints: ["Adjustable conveyor speed", "Compact vertical design"],
      applications: ["Burger shops", "Quick-service restaurants", "Snack food operations"],
      packageInfo: ["Carton packing size: 520 x 350 x 610 mm", "Net weight: 23 kg", "Gross weight: 25 kg"],
      notes: "Original model appears to be a capacity label and requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "jn-40",
      model: "JN-40",
      category: "preparation-equipment",
      name: "JUNNUO Vertical Burger Machine JN-40",
      description: "Commercial vertical burger machine for fast food preparation lines.",
      specs: ["Voltage: 220V/50Hz", "Power: 2 kW", "Machine size: 630 x 200 x 660 mm"],
      sellingPoints: ["Vertical preparation format", "Commercial kitchen construction"],
      applications: ["Burger shops", "Quick-service restaurants", "Food preparation lines"],
      packageInfo: ["Carton packing size: 520 x 350 x 610 mm", "Net weight: 38 kg", "Gross weight: 44 kg", "Carton with plywood frame"],
      notes: "Packing size requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "vf-60",
      model: "VF-60",
      category: "preparation-equipment",
      name: "JUNNUO French Fry Work Station VF-60",
      description: "French fry work station for organizing and holding fried potato products.",
      specs: ["Voltage: 220V/50Hz", "Power: 0.75 kW", "Machine size: 600 x 700 x 1530 mm"],
      sellingPoints: ["Organized service station", "Suitable for fast food operations"],
      applications: ["French fry stations", "Fast food kitchens", "Snack food service"],
      packageInfo: ["Packing size: 680 x 810 x 1620 mm", "Net weight: 50 kg", "Gross weight: 70 kg", "Carton with plywood frame"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "vf-98",
      model: "VF-98",
      category: "preparation-equipment",
      name: "JUNNUO French Fry Work Station VF-98",
      description: "Large French fry work station for commercial service counters.",
      specs: ["Voltage: 220V/50Hz", "Power: 0.75 kW", "Machine size: 1000 x 700 x 1500 mm"],
      sellingPoints: ["Larger work surface", "Designed for commercial food service"],
      applications: ["French fry stations", "Fast food kitchens", "Snack food service"],
      packageInfo: ["Packing size: 1060 x 770 x 1550 mm", "Net weight: 75 kg", "Gross weight: 105 kg"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "jn-501",
      model: "JN-501",
      category: "holding-cabinets",
      name: "JUNNUO Vertical Heated Holding Cabinet JN-501",
      description: "Five-tray vertical heated holding cabinet for prepared food service.",
      specs: ["Voltage: 220V/50Hz", "Power: 1.3 kW", "Temperature range: 0-85 C", "Capacity: 5 trays", "Machine size: 780 x 645 x 1175 mm"],
      sellingPoints: ["Vertical heated storage", "Suitable for prepared food holding"],
      applications: ["Fried chicken stores", "Catering operations", "Quick-service restaurants"],
      packageInfo: ["Packing size: 900 x 770 x 1300 mm", "Net weight: 90 kg", "Gross weight: 105 kg", "Carton with plywood frame"],
      notes: "Door configuration requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "jn-901a",
      model: "JN-901A",
      category: "holding-cabinets",
      name: "JUNNUO Vertical Heated Holding Cabinet JN-901A",
      description: "Nine-tray vertical heated holding cabinet for high-volume food service.",
      specs: ["Voltage: 220V/50Hz", "Power: 2.6 kW", "Temperature range: 0-85 C", "Capacity: 9 trays", "Machine size: 835 x 645 x 1880 mm"],
      sellingPoints: ["High tray capacity", "Commercial heated holding performance"],
      applications: ["Fried chicken stores", "Catering operations", "Quick-service restaurants"],
      packageInfo: ["Packing size: 1000 x 770 x 1980 mm", "Net weight: 155 kg", "Gross weight: 185 kg", "Carton with plywood frame"],
      notes: "Door configuration requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "jh-1200",
      model: "JH-1200",
      category: "holding-cabinets",
      name: "JUNNUO Heated Display Cabinet JH-1200",
      description: "Heated display cabinet for presenting warm prepared food.",
      specs: ["Voltage: 220V/50Hz", "Power: 3.1 kW", "Machine size: 1200 x 710 x 890 mm"],
      sellingPoints: ["Warm food display", "Commercial counter service format"],
      applications: ["Food displays", "Restaurants", "Quick-service counters"],
      packageInfo: ["Packing size: 1280 x 780 x 1090 mm", "Net weight: 105 kg"],
      notes: "Gross weight is missing",
      image: "",
      primary: true,
    },
    {
      id: "jh-1500",
      model: "JH-1500",
      category: "holding-cabinets",
      name: "JUNNUO Heated Display Cabinet JH-1500",
      description: "Wide heated display cabinet for warm prepared food presentation.",
      specs: ["Voltage: 220V/50Hz", "Power: 3.1 kW", "Machine size: 1500 x 710 x 890 mm"],
      sellingPoints: ["Wide display format", "Commercial counter service design"],
      applications: ["Food displays", "Restaurants", "Quick-service counters"],
      packageInfo: ["Packing size: 1580 x 780 x 1090 mm", "Net weight: 135 kg"],
      notes: "Current Chinese name and gross weight are missing",
      image: "",
      primary: true,
    },
    {
      id: "jn-8p",
      model: "JN-8P",
      category: "holding-cabinets",
      name: "JUNNUO Heated Holding Cabinet JN-8P",
      description: "Heated holding cabinet with top tray area for commercial food service.",
      specs: ["Voltage: 220-240V/50Hz", "Power: 2.8 kW", "Machine size: 1200 x 750 x 860 mm", "Top tray: 37 x 26 cm"],
      sellingPoints: ["Water tray included", "Bottom humidity heating", "CE certified"],
      applications: ["Prepared food holding", "Fried chicken stores", "Quick-service restaurants"],
      packageInfo: ["Packing size: 1290 x 890 x 940 mm", "Net weight: 80 kg", "Gross weight: 95 kg"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "center-island-cabinet-1200",
      model: "1.2米长",
      displayModel: "1200 mm",
      category: "preparation-equipment",
      name: "JUNNUO Center Island Cabinet 1200 mm",
      description: "Center island cabinet for commercial kitchen preparation areas.",
      specs: ["Machine size: 1200 x 760 x 800 mm"],
      sellingPoints: ["Stainless work area", "Suitable for kitchen preparation zones"],
      applications: ["Commercial kitchens", "Preparation rooms", "Food service work areas"],
      packageInfo: ["Net weight: 45 kg", "Gross weight: 60 kg"],
      notes: "Original model is a length description and requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "center-island-cabinet-1500",
      model: "1.5米长",
      displayModel: "1500 mm",
      category: "preparation-equipment",
      name: "JUNNUO Center Island Cabinet 1500 mm",
      description: "Long center island cabinet for commercial kitchen preparation areas.",
      specs: ["Machine size: 1520 x 760 x 800 mm"],
      sellingPoints: ["Long preparation surface", "Suitable for kitchen preparation zones"],
      applications: ["Commercial kitchens", "Preparation rooms", "Food service work areas"],
      packageInfo: ["Net weight: 60 kg", "Gross weight: 85 kg"],
      notes: "Original model is duplicated by another product and requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "refrigerated-preparation-counter-1500",
      model: "1.5米长",
      displayModel: "1500 mm",
      category: "refrigeration-equipment",
      name: "JUNNUO Refrigerated Preparation Counter 1500 mm",
      description: "Refrigerated preparation counter for chilled food storage and preparation.",
      specs: ["Voltage: 220V/50Hz", "Power: 152 W", "Capacity: 368 L", "Temperature range: -5 C to 10 C", "Machine size: 1500 x 800 x 800 mm"],
      sellingPoints: ["Commercial compressor", "Electronic temperature control", "Removable door gasket", "High-density insulation"],
      applications: ["Cold preparation counters", "Restaurants", "Commercial kitchens"],
      packageInfo: ["Net weight: 80 kg", "Gross weight: 98 kg"],
      notes: "Original model is duplicated by another product and requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "four-door-refrigerated-cabinet",
      model: "四门",
      displayModel: "Four-Door",
      category: "refrigeration-equipment",
      name: "JUNNUO Four-Door Refrigerated Cabinet",
      description: "Four-door single-temperature refrigerated cabinet for commercial kitchens.",
      specs: ["Voltage: 220V/50Hz", "Power: 236 W", "Capacity: 880 L", "Temperature range: -5 C to +10 C", "Machine size: 1210 x 700 x 1890 mm"],
      sellingPoints: ["Four-door storage format", "Commercial refrigeration capacity"],
      applications: ["Restaurant storage", "Commercial kitchens", "Food service refrigeration"],
      packageInfo: ["Net weight: 115 kg", "Gross weight: 135 kg"],
      notes: "Original model is a door description and requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "six-door-dual-temperature-refrigerator",
      model: "六门",
      displayModel: "Six-Door",
      category: "refrigeration-equipment",
      name: "JUNNUO Six-Door Dual-Temperature Refrigerator",
      description: "Six-door dual-temperature refrigerator for commercial kitchen storage.",
      specs: ["Voltage: 220V/50Hz", "Power: 236 W", "Capacity: 1305 L", "Temperature range: -5 C to 10 C and -5 C to -18 C", "Machine size: 1820 x 700 x 1915 mm"],
      sellingPoints: ["Dual-temperature storage", "Large commercial capacity"],
      applications: ["Restaurant storage", "Commercial kitchens", "Food service refrigeration"],
      packageInfo: ["Net weight: 115 kg", "Gross weight: 135 kg"],
      notes: "Original model is a door description and requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "ofe-301s",
      model: "OFE-301S",
      category: "open-fryers",
      name: "JUNNUO Electric Open Fryer with Basket Lift OFE-301S",
      description: "Electric open fryer with basket lift function for commercial frying operations.",
      specs: ["Voltage: 3N~380V/50Hz", "Power: 14.2 kW", "Oil capacity: 26 L", "Temperature range: room temperature to 200 C", "Machine size: 450 x 860 x 1130 mm"],
      sellingPoints: ["304 food-grade stainless steel tank", "Cold zone tank design", "Computer control with 12 cooking programs", "Integrated oil filtration system", "Automatic basket lift"],
      applications: ["Fried chicken shops", "Fast food restaurants", "Commercial frying stations"],
      packageInfo: ["Packing size: 490 x 930 x 1250 mm", "Net weight: 100 kg", "Gross weight: 110 kg", "Fully enclosed plywood export packing"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "ofe-301",
      model: "OFE-301",
      category: "open-fryers",
      name: "JUNNUO Electric Open Fryer OFE-301",
      description: "Single-tank electric open fryer with two baskets and built-in oil filtration.",
      specs: ["Voltage: 3N~380V/50Hz", "Power: 14.2 kW", "Oil capacity: 26 L", "Temperature range: room temperature to 200 C", "Machine size: 450 x 860 x 1130 mm"],
      sellingPoints: ["304 food-grade stainless steel tank", "Single tank with dual baskets", "Computer control with 12 cooking programs", "Built-in oil filtration system", "CE certified"],
      applications: ["Fast food kitchens", "Fried food counters", "Commercial frying stations"],
      packageInfo: ["Packing size: 490 x 930 x 1250 mm", "Net weight: 80 kg", "Gross weight: 100 kg", "Fully enclosed plywood export packing"],
      notes: "Specification requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "ofg-301",
      model: "OFG-301",
      category: "open-fryers",
      name: "JUNNUO Gas Open Fryer OFG-301",
      description: "Single-tank gas open fryer with two baskets and built-in oil filtration.",
      specs: ["Voltage: 220V/50Hz", "Energy source: LPG or natural gas", "Oil capacity: 26 L", "Temperature range: room temperature to 200 C", "Machine size: 450 x 860 x 1130 mm"],
      sellingPoints: ["Gas heating", "304 stainless steel tank", "Computer control panel", "Built-in oil filtration system"],
      applications: ["Fast food kitchens", "Fried food counters", "Commercial frying stations"],
      packageInfo: ["Packing size: 490 x 930 x 1250 mm", "Net weight: 90 kg", "Gross weight: 110 kg"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "ofe-302",
      model: "OFE-302",
      category: "open-fryers",
      name: "JUNNUO Double-Tank Electric Open Fryer OFE-302",
      description: "Double-tank electric open fryer with four baskets for higher frying capacity.",
      specs: ["Voltage: 3N~380V/50Hz", "Power: 27.7 kW", "Oil capacity: 26 L + 26 L", "Temperature range: room temperature to 200 C", "Machine size: 850 x 860 x 1130 mm"],
      sellingPoints: ["Double-tank layout", "Four-basket operation", "Computer control panel", "Built-in oil filtration system"],
      applications: ["High-volume fried food service", "Fast food kitchens", "Commercial frying stations"],
      packageInfo: ["Packing size: 870 x 910 x 1250 mm", "Net weight: 120 kg", "Gross weight: 140 kg"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "ofg-302",
      model: "OFG-302",
      category: "open-fryers",
      name: "JUNNUO Double-Tank Gas Open Fryer OFG-302",
      description: "Double-tank gas open fryer with four baskets for commercial frying lines.",
      specs: ["Voltage: 220V/50Hz", "Energy source: LPG or natural gas", "Oil capacity: 26 L + 26 L", "Temperature range: room temperature to 200 C", "Machine size: 850 x 860 x 1130 mm"],
      sellingPoints: ["Gas heating", "Double-tank layout", "Four-basket operation", "Built-in oil filtration system"],
      applications: ["High-volume fried food service", "Fast food kitchens", "Commercial frying stations"],
      packageInfo: ["Packing size: 870 x 910 x 1250 mm", "Net weight: 130 kg", "Gross weight: 158 kg"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "pfe-24",
      model: "PFE-24",
      category: "pressure-fryers",
      name: "JUNNUO Electric Pressure Fryer PFE-24",
      description: "Mechanical electric pressure fryer for commercial fried chicken preparation.",
      specs: ["Voltage: 3N~380V/50Hz", "Power: 13.5 kW", "Oil capacity: 24 L", "Temperature range: room temperature to 200 C", "Machine size: 450 x 960 x 1220 mm"],
      sellingPoints: ["Stainless steel construction", "Lightweight aluminum lid", "Heavy-duty casters with brakes", "Simple mechanical control", "CE certified"],
      applications: ["Fried chicken restaurants", "Fast food kitchens", "Commercial catering"],
      packageInfo: ["Packing size: 490 x 1050 x 1310 mm", "Net weight: 100 kg", "Gross weight: 120 kg", "Fully enclosed plywood export packing"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "pfg-25",
      model: "PFG-25",
      category: "pressure-fryers",
      name: "JUNNUO Gas Pressure Fryer PFG-25",
      description: "Mechanical gas pressure fryer for commercial fried chicken preparation.",
      specs: ["Voltage: 220V/50Hz", "Energy source: LPG or natural gas", "Oil capacity: 25 L", "Temperature range: room temperature to 200 C", "Machine size: 450 x 960 x 1220 mm"],
      sellingPoints: ["Gas heating", "Mechanical control panel", "No built-in filter", "Commercial pressure frying structure"],
      applications: ["Fried chicken restaurants", "Fast food kitchens", "Commercial catering"],
      packageInfo: ["Packing size: 490 x 1050 x 1310 mm", "Net weight: 110 kg", "Gross weight: 125 kg"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "pfe-600",
      model: "PFE-600",
      category: "pressure-fryers",
      name: "JUNNUO Electric Pressure Fryer PFE-600",
      description: "Computer-controlled electric pressure fryer with built-in oil filtration.",
      specs: ["Voltage: 3N~380V/50Hz", "Power: 13.5 kW", "Oil capacity: 24 L", "Temperature range: room temperature to 200 C", "Machine size: 460 x 960 x 1230 mm"],
      sellingPoints: ["304 food-grade stainless steel tank", "Built-in automatic oil filtration", "Computer control panel", "Ten stored cooking keys", "CE certified"],
      applications: ["Fried chicken restaurants", "Fast food kitchens", "Commercial catering"],
      packageInfo: ["Packing size: 490 x 1050 x 1310 mm", "Net weight: 120 kg", "Gross weight: 135 kg", "Fully enclosed plywood export packing"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "pfg-600",
      model: "PFG-600",
      category: "pressure-fryers",
      name: "JUNNUO Gas Pressure Fryer PFG-600",
      description: "Computer-controlled gas pressure fryer with built-in oil filtration.",
      specs: ["Voltage: 220V/50Hz", "Power: 0.75 kW", "Energy source: LPG or natural gas", "Oil capacity: 25 L", "Temperature range: room temperature to 200 C", "Machine size: 460 x 960 x 1230 mm"],
      sellingPoints: ["Gas pressure frying", "Computer control panel", "Built-in oil filtration system", "Commercial stainless steel structure"],
      applications: ["Fried chicken restaurants", "Fast food kitchens", "Commercial catering"],
      packageInfo: ["Packing size: 490 x 1050 x 1310 mm", "Net weight: 135 kg", "Gross weight: 150 kg"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "pfe-800",
      model: "PFE-800",
      category: "pressure-fryers",
      name: "JUNNUO Programmable Electric Pressure Fryer PFE-800",
      description: "Programmable electric pressure fryer with computer control and built-in oil filtration.",
      specs: ["Voltage: 3N~380V/50Hz", "Power: 13.5 kW", "Oil capacity: 24 L", "Temperature range: room temperature to 200 C", "Machine size: 460 x 960 x 1230 mm"],
      sellingPoints: ["304 food-grade stainless steel tank", "Built-in automatic oil filtration", "Programmable computer control", "Multi-stage timing, temperature control, and exhaust", "CE certified"],
      applications: ["Fried chicken restaurants", "Fast food chains", "Commercial catering"],
      packageInfo: ["Packing size: 490 x 1050 x 1310 mm", "Net weight: 120 kg", "Gross weight: 135 kg", "Fully enclosed plywood export packing"],
      notes: "Specification requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "pfg-800",
      model: "PFG-800",
      category: "pressure-fryers",
      name: "JUNNUO Programmable Gas Pressure Fryer PFG-800",
      description: "Programmable gas pressure fryer with computer control and built-in oil filtration.",
      specs: ["Voltage: 220V/50Hz", "Power: 0.75 kW", "Energy source: LPG or natural gas", "Oil capacity: 25 L", "Temperature range: room temperature to 200 C", "Machine size: 460 x 960 x 1230 mm"],
      sellingPoints: ["Gas pressure frying", "Built-in oil filtration system", "Programmable computer control", "Multi-stage timing, temperature control, and exhaust"],
      applications: ["Fried chicken restaurants", "Fast food chains", "Commercial catering"],
      packageInfo: ["Packing size: 490 x 1050 x 1310 mm", "Net weight: 135 kg", "Gross weight: 150 kg"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "pfe-5910",
      model: "PFE-5910",
      category: "pressure-fryers",
      name: "JUNNUO 8-Head Electric Pressure Fryer PFE-5910",
      description: "Large-capacity electric pressure fryer for high-volume fried chicken production.",
      specs: ["Voltage: 3N~380V/50Hz", "Power: 17 kW", "Oil capacity: 45 L", "Temperature range: room temperature to 200 C", "Machine size: 1040 x 615 x 1530 mm"],
      sellingPoints: ["Large 8-head capacity", "304 stainless steel tank", "Computer control panel", "Built-in oil filtration system"],
      applications: ["High-volume fried chicken restaurants", "Central kitchens", "Commercial catering"],
      packageInfo: ["Packing size: 1150 x 680 x 1720 mm", "Net weight: 345 kg", "Gross weight: 375 kg"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "pfg-5910",
      model: "PFG-5910",
      category: "pressure-fryers",
      name: "JUNNUO 8-Head Gas Pressure Fryer PFG-5910",
      description: "Large-capacity gas pressure fryer for high-volume fried chicken production.",
      specs: ["Voltage: 220V/50Hz", "Energy source: LPG or natural gas", "Oil capacity: 45 L", "Temperature range: room temperature to 200 C", "Machine size: 460 x 960 x 1230 mm"],
      sellingPoints: ["Large 8-head capacity", "Gas pressure frying", "Computer control panel", "Built-in oil filtration system"],
      applications: ["High-volume fried chicken restaurants", "Central kitchens", "Commercial catering"],
      packageInfo: ["Packing size: 490 x 1050 x 1310 mm", "Net weight: 135 kg", "Gross weight: 150 kg"],
      notes: "Specification requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "ofe-5910",
      model: "OFE-5910",
      category: "open-fryers",
      name: "JUNNUO 8-Head Electric Open Fryer OFE-5910",
      description: "Large-capacity electric open fryer for high-volume fried food production.",
      specs: ["Voltage: 3N~380V/50Hz", "Power: 17 kW", "Oil capacity: 45 L", "Temperature range: room temperature to 200 C", "Machine size: 1040 x 615 x 1530 mm"],
      sellingPoints: ["Large 8-head capacity", "304 stainless steel tank", "Computer control panel", "Built-in oil filtration system"],
      applications: ["High-volume fried food service", "Central kitchens", "Commercial frying stations"],
      packageInfo: ["Packing size: 1150 x 680 x 1720 mm", "Net weight: 345 kg", "Gross weight: 375 kg"],
      notes: "",
      image: "",
      primary: true,
    },
    {
      id: "ofg-5910",
      model: "OFG-5910",
      category: "open-fryers",
      name: "JUNNUO 8-Head Gas Open Fryer OFG-5910",
      description: "Large-capacity gas open fryer for high-volume fried food production.",
      specs: ["Voltage: 220V/50Hz", "Energy source: LPG or natural gas", "Oil capacity: 45 L", "Temperature range: room temperature to 200 C", "Machine size: 460 x 960 x 1230 mm"],
      sellingPoints: ["Large 8-head capacity", "Gas frying", "Computer control panel", "Built-in oil filtration system"],
      applications: ["High-volume fried food service", "Central kitchens", "Commercial frying stations"],
      packageInfo: ["Packing size: 490 x 1050 x 1310 mm", "Net weight: 135 kg", "Gross weight: 150 kg"],
      notes: "Specification requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "jh-16",
      model: "JH-16",
      category: "pressure-fryers",
      name: "JUNNUO Countertop Pressure Fryer JH-16",
      description: "Countertop electric pressure fryer for compact commercial frying applications.",
      specs: ["Tank capacity: 16 L", "Power source: Electric", "Voltage: 220-240V/50Hz or 110V/60Hz", "Power: 3 kW", "Machine size: 450 x 960 x 1230 mm"],
      sellingPoints: ["Countertop pressure fryer format", "Compact commercial application", "One-year warranty listed in source quotation"],
      applications: ["Small fried chicken shops", "Commercial test kitchens", "Compact food service counters"],
      packageInfo: ["Packing size: 510 x 1030 x 131 mm", "Net weight: 21 kg", "Gross weight: 25 kg"],
      notes: "Specification requires confirmation",
      image: "",
      primary: true,
    },
    {
      id: "fryer-filter-paper",
      model: "",
      category: "accessories",
      name: "JUNNUO Fryer Filter Paper",
      description: "Filter paper accessory for fryer oil filtration.",
      specs: ["Size: 45 x 29 cm"],
      sellingPoints: ["Designed for fryer filtration use"],
      applications: ["Fryer oil filtration", "Commercial frying stations"],
      packageInfo: ["100 sheets per carton"],
      notes: "Accessory has no model in the source Excel and is not a default main product",
      image: "",
      primary: false,
    },
    {
      id: "fryer-cleaning-five-piece-set",
      model: "",
      category: "accessories",
      name: "JUNNUO Fryer Cleaning Five-Piece Set",
      description: "Five-piece cleaning accessory set for fryer maintenance.",
      specs: ["Heat-resistant cleaning set"],
      sellingPoints: ["Designed for fryer cleaning and maintenance"],
      applications: ["Fryer cleaning", "Kitchen maintenance"],
      packageInfo: [],
      notes: "Accessory has no model in the source Excel and is not a default main product",
      image: "",
      primary: false,
    },
  ];

  return { CATEGORIES, PRODUCTS };
});
